### ISSUE TITLE
Missing divalent carbon to halogens

### ISSUE THREAD

**Issue by bannanc** [open-forcefield-group/smirnoff99Frosst#27]
Right now we only have very specific carbon-halogen bonds. Here is the section from smirffishFrcmod:
```
[#6X4:1]-[#9:2]                  367.0  1.380   parm99
[#6X3:1]-[#9:2]                  386.0  1.359   parm99
[#6X4:1]-[#17:2]                 232.0  1.766   parm99
[#6X3:1]-[#17:2]                 193.0  1.727   parm99
[#6X4:1]-[#35:2]                 159.0  1.944   parm99 Br-CT
[#6X3:1]-[#35:2]                 172.0  1.890   parm99 Br-CA
[#6X4:1]-[#53:2]                  148.0  2.166   parm99 I_-CT
[#6X3:1]-[#53:2]                  171.0  2.075   parm99 I_-CA
```
I understand that the hybridization around carbon will affect the strength of the C-(halgen) bond. 

There are two options:

1. If we don't want to add more parameters, I would suggest making the `#6X3` entries just `#6` and moving them above the `#6X4`. Since I would expect Sp carbons to resemble Sp2 carbons more than Sp3 carbons.

2. Alternatively, I pulled the divalent carbon options from GAFF2. c1 is the Sp carbon in GAFF2 (well the only one that gets halogen bonds).

```
c1-i   153.51   1.989                     SOURCE2       4    0.0032
br-c1  227.01   1.787                     SOURCE2       4    0.0024
c1-cl  261.49   1.631                     SOURCE2       6    0.0050
c1-f   482.19   1.270                     SOURCE2       2    0.0085
```

Corresponding SMIRFF parameters:

```
[#6X2:1]-[#53:2]   150.   2.0                    
[#6X2:1]-[#35:2]  230.   1.8                  
[#6X2:1]-[#17:2]  260.   1.6                     
[#6X2:1]-[#9:2]   480.   1.3                     
```

**Comment by bannanc** [comment]
@davidlmobley 
I would give preference to option 1 for now

**Comment by davidlmobley** [comment]
I like option 1, yes, @bannanc . As noted, GAFF2 is as yet unpublished, so I don't see a strong reason to prefer adopting/adapting GAFF2 parameters over just generalizing parameters we already have (except when the GAFF2 parameters actually cover chemical space that is very different from what we already cover). This is especially true since we're planning on revisiting this chemical space anyway with reference QM calculations to improve on our starting point.

So, for now I prefer option 1 -- just generalizing our current parameters, not adding more. Adding more can come when we do QM studies.

**Comment by bannanc** [comment]
in pull request #43
